# Develop override settings

url: http://localhost:4000


# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : 

comments:
  disqus:
    shortname            : "mmistakes-dev"

sass:
  style: expanded
