# Develop override settings

url: http://localhost:4000

# Analytics
analytics:
  provider               : "google" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "G-08N6F6EFQP"

comments:
  disqus:
    shortname            : "mmistakes-dev"

sass:
  style: expanded
